// YSpot's own icons -- drawn, not vendored.
//
// Windows Security and Windows Backup have no icon in the Fluent UI System
// Icons set, and Microsoft's shipped artwork for them is not ours to
// redistribute, so without these two both rows wear the Windows Settings
// glyph and three rows in the launcher look identical.
//
// Copyright (c) the YSpot authors, under YSpot's own licence. These are
// original drawings. What they take from Microsoft's Fluent iconography is
// its published grid -- a 20 box, a 2 margin, a 16 live area, the keylines
// and the stroke chart, all recorded in docs/icon-grid.md -- so that they sit
// beside the vendored set without looking like guests. A grid is a
// measurement, not artwork.
//
// GENERATED by scripts/draw-yspot-icons.py -- do not edit by hand.

/** viewBox for every path here, the same as the vendored set. */
export const YSPOT_VIEWBOX = "0 0 20 20";

/** Icon key to SVG path data, drawn at the 20px size. */
export const YSPOT_20: Readonly<Record<string, string>> = {
  yspot_backup_restore: "M6.5 2L15 2C16.657 2 18 3.343 18 5L18 13.5C18 14.052 17.552 14.5 17 14.5C16.448 14.5 16 14.052 16 13.5L16 5C16 4.448 15.552 4 15 4L6.5 4C5.948 4 5.5 3.552 5.5 3C5.5 2.448 5.948 2 6.5 2ZM5 5.5L11.5 5.5C13.157 5.5 14.5 6.843 14.5 8.5L14.5 15C14.5 16.657 13.157 18 11.5 18L5 18C3.343 18 2 16.657 2 15L2 8.5C2 6.843 3.343 5.5 5 5.5ZM11.82 10.308L10.243 10.945C10.582 11.783 10.36 12.743 9.689 13.348C9.017 13.953 8.039 14.073 7.241 13.648C6.443 13.224 5.995 12.346 6.121 11.451C6.247 10.556 6.919 9.835 7.803 9.647L7.98 10.478L10.365 8.233L7.273 7.153L7.45 7.984C5.866 8.321 4.663 9.611 4.437 11.214C4.212 12.817 5.013 14.389 6.443 15.149C7.872 15.909 9.623 15.694 10.826 14.611C12.029 13.528 12.426 11.808 11.82 10.308Z",
  yspot_windows_shield: "M5.5 2L14.5 2C15.33 2 16 2.67 16 3.5L16 9.8C16 13.6 13.4 16.85 10.3 17.95C10.1 18.02 9.9 18.02 9.7 17.95C6.6 16.85 4 13.6 4 9.8L4 3.5C4 2.67 4.67 2 5.5 2ZM7 4.5C6.724 4.5 6.5 4.724 6.5 5L6.5 6.75C6.5 7.026 6.724 7.25 7 7.25L8.75 7.25C9.026 7.25 9.25 7.026 9.25 6.75L9.25 5C9.25 4.724 9.026 4.5 8.75 4.5L7 4.5ZM11.25 4.5C10.974 4.5 10.75 4.724 10.75 5L10.75 6.75C10.75 7.026 10.974 7.25 11.25 7.25L13 7.25C13.276 7.25 13.5 7.026 13.5 6.75L13.5 5C13.5 4.724 13.276 4.5 13 4.5L11.25 4.5ZM7 8.75C6.724 8.75 6.5 8.974 6.5 9.25L6.5 11C6.5 11.276 6.724 11.5 7 11.5L8.75 11.5C9.026 11.5 9.25 11.276 9.25 11L9.25 9.25C9.25 8.974 9.026 8.75 8.75 8.75L7 8.75ZM11.25 8.75C10.974 8.75 10.75 8.974 10.75 9.25L10.75 11C10.75 11.276 10.974 11.5 11.25 11.5L13 11.5C13.276 11.5 13.5 11.276 13.5 11L13.5 9.25C13.5 8.974 13.276 8.75 13 8.75L11.25 8.75Z",
};
