// YSpot's own icons -- drawn, not vendored.
//
// Windows Security and Windows Backup have no icon in the Fluent UI System
// Icons set, and Microsoft's shipped artwork for them is not ours to
// redistribute, so without these two both rows wear the Windows Settings
// glyph and three rows in the launcher look identical.
//
// Copyright (c) the YSpot authors, under YSpot's own licence. These are
// original drawings. What they take from Microsoft's Fluent iconography is
// its published grid -- a 20 box, a 2 margin, a 16 live area, the keylines
// and the 1px Regular stroke, all recorded in docs/icon-grid.md -- so that
// they sit beside the vendored set without looking like guests. A grid is a
// measurement, not artwork.
//
// GENERATED by scripts/draw-yspot-icons.py -- do not edit by hand.

/** viewBox for every path here, the same as the vendored set. */
export const YSPOT_VIEWBOX = "0 0 20 20";

/** Icon key to SVG path data, drawn at the 20px size. */
export const YSPOT_20: Readonly<Record<string, string>> = {
  yspot_backup_restore: "M6 2L15 2C16.657 2 18 3.343 18 5L18 14C18 14.276 17.776 14.5 17.5 14.5C17.224 14.5 17 14.276 17 14L17 5C17 3.895 16.105 3 15 3L6 3C5.724 3 5.5 2.776 5.5 2.5C5.5 2.224 5.724 2 6 2ZM5 5.5L11.5 5.5C13.157 5.5 14.5 6.843 14.5 8.5L14.5 15C14.5 16.657 13.157 18 11.5 18L5 18C3.343 18 2 16.657 2 15L2 8.5C2 6.843 3.343 5.5 5 5.5ZM5 6.5C3.895 6.5 3 7.395 3 8.5L3 15C3 16.105 3.895 17 5 17L11.5 17C12.605 17 13.5 16.105 13.5 15L13.5 8.5C13.5 7.395 12.605 6.5 11.5 6.5L5 6.5ZM11.402 10.476C11.938 11.802 11.587 13.32 10.525 14.277C9.463 15.233 7.916 15.423 6.654 14.752C5.392 14.081 4.684 12.692 4.883 11.277C5.082 9.861 6.145 8.721 7.543 8.424L7.366 7.593L9.897 8.435L7.928 10.234L7.751 9.402C6.764 9.612 6.014 10.417 5.873 11.416C5.733 12.415 6.232 13.395 7.123 13.869C8.014 14.343 9.106 14.209 9.856 13.534C10.606 12.858 10.853 11.786 10.475 10.851L11.402 10.476Z",
  yspot_windows_shield: "M7 2L13 2C13.797 2 14.604 2.361 15.121 2.879C15.639 3.396 16 4.203 16 5L16 9.6C16 11.391 15.303 13.238 14.293 14.696C13.282 16.156 11.862 17.364 10.46 17.906C10.195 17.999 9.805 17.999 9.555 17.912C8.138 17.364 6.718 16.156 5.707 14.696C4.697 13.238 4 11.391 4 9.6L4 5C4 4.203 4.361 3.396 4.879 2.879C5.396 2.361 6.203 2 7 2ZM7 3C6.416 3 5.973 3.199 5.586 3.586C5.199 3.973 5 4.416 5 5L5 9.6C5 11.209 5.59 12.77 6.529 14.126C7.466 15.479 8.656 16.492 9.9 16.974C9.975 16.999 10.025 16.999 10.115 16.968C11.344 16.492 12.534 15.479 13.471 14.126C14.41 12.77 15 11.209 15 9.6L15 5C15 4.416 14.801 3.973 14.414 3.586C14.027 3.199 13.584 3 13 3L7 3ZM7.4 5.75L8.6 5.75C8.821 5.75 9 5.929 9 6.15L9 7.35C9 7.571 8.821 7.75 8.6 7.75L7.4 7.75C7.179 7.75 7 7.571 7 7.35L7 6.15C7 5.929 7.179 5.75 7.4 5.75ZM10.9 5.75L12.1 5.75C12.321 5.75 12.5 5.929 12.5 6.15L12.5 7.35C12.5 7.571 12.321 7.75 12.1 7.75L10.9 7.75C10.679 7.75 10.5 7.571 10.5 7.35L10.5 6.15C10.5 5.929 10.679 5.75 10.9 5.75ZM7.4 9.25L8.6 9.25C8.821 9.25 9 9.429 9 9.65L9 10.85C9 11.071 8.821 11.25 8.6 11.25L7.4 11.25C7.179 11.25 7 11.071 7 10.85L7 9.65C7 9.429 7.179 9.25 7.4 9.25ZM10.9 9.25L12.1 9.25C12.321 9.25 12.5 9.429 12.5 9.65L12.5 10.85C12.5 11.071 12.321 11.25 12.1 11.25L10.9 11.25C10.679 11.25 10.5 11.071 10.5 10.85L10.5 9.65C10.5 9.429 10.679 9.25 10.9 9.25Z",
};
