"""Vendor Fluent UI System Icons path data into the frontend.

A one-off developer tool, not part of the build. It reads the icon keys out of
the mapping tables in the spec, fetches each icon at a PINNED upstream commit,
asserts the file is the shape the renderer assumes, and emits
`apps/shell/src/lib/fluentGlyphs.ts`.

Why fetch rather than transcribe: 99 path strings copied by hand is 99 chances
to corrupt one silently, and a corrupted path renders as a plausible-looking
wrong drawing rather than an error. The assertions in `extract` are the other
half of that — an icon whose upstream shape changes announces itself here
instead of rendering wrong in the launcher.

Licence: Fluent UI System Icons is MIT, (c) 2020 Microsoft Corporation. The
obligation is to carry the copyright and permission notice, which the emitted
file's header and THIRD-PARTY-NOTICES.md both do.

Usage:  python scripts/vendor-fluent-icons.py <path-to-spec.md>
"""

import io
import os
import re
import sys
import urllib.parse
import urllib.request

# Pinned, never `main`: the recorded provenance and the file contents must not
# be able to disagree. Update deliberately, and the diff is then reviewable.
SHA = "5bae3fb7771054c252a54b1d9210e9c03439fa1b"
RAW = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/" + SHA

# Title Case of the key, except where upstream's directory does not follow it.
DIR_EXCEPTIONS = {
    "sim": "SIM",
    "usb_plug": "USB Plug",
    "wifi_1": "WiFi 1",
    "wifi_settings": "WiFi Settings",
}

OUT = "apps/shell/src/lib/fluentGlyphs.ts"

HEADER = '''// Fluent UI System Icons — vendored path data.
//
// Source: https://github.com/microsoft/fluentui-system-icons
// Commit: {sha}
//
// MIT License. Copyright (c) 2020 Microsoft Corporation.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.
//
// The full notice also ships beside the executable as THIRD-PARTY-NOTICES.md.
//
// GENERATED by scripts/vendor-fluent-icons.py — do not edit by hand.
//
// Each key K comes from assets/<Concept>/SVG/ic_fluent_<K>_20_regular.svg.
// Upstream's fill="#212121" and root fill="none" are stripped, which is what
// upstream's own build does: keeping the hex literal renders near-black in
// dark theme and ignores forced-colors entirely, because the user agent forces
// `color`, not `fill`.
//
// NOT Segoe Fluent Icons. That font is covered by the revocable Microsoft
// Fabric Assets Agreement, its own name table says "any other use is
// prohibited", and Microsoft's font FAQ forbids converting Windows fonts to
// other formats — so tracing a Segoe glyph into this file would be an
// infringement that looks, in the diff, exactly like the compliant thing.
//
// Do not add an icon that depicts a brand (Xbox, Store, Word, App Store).
// Trademark rights are separate from the copyright licence above.

/** viewBox for every path here. */
export const FLUENT_VIEWBOX = "0 0 20 20";

/** Icon key to SVG path data, at the 20px regular size. */
export const FLUENT_20: Readonly<Record<string, string>> = {{
'''


def concept_dir(key: str) -> str:
    if key in DIR_EXCEPTIONS:
        return DIR_EXCEPTIONS[key]
    return " ".join(w.capitalize() for w in key.split("_"))


def keys_from_spec(spec: str):
    """Every distinct icon key named in the spec's mapping tables."""
    found = []
    for row in re.findall(r"^\|.*\|$", spec, re.M):
        cells = [c.strip() for c in row.strip("|").split("|")]
        for c in cells:
            m = re.fullmatch(r"`([a-z0-9_]+)`", c)
            if m and not m.group(1).startswith("ms_"):
                found.append(m.group(1))
    # Preserve first-seen order for a stable diff, then sort at emit time.
    seen, out = set(), []
    for k in found:
        if k not in seen:
            seen.add(k)
            out.append(k)
    return out


def extract(key: str, svg: str) -> str:
    """The single path's `d`, with the assertions that keep this honest."""
    paths = re.findall(r"<path\b[^>]*>", svg)
    if len(paths) != 1:
        raise ValueError(f"{key}: expected exactly one <path>, found {len(paths)}")
    tag = paths[0]
    if "fill-rule" in tag or "stroke" in tag:
        raise ValueError(f"{key}: path carries fill-rule or stroke, which the renderer does not apply")
    for fill in re.findall(r'fill="([^"]*)"', svg):
        if fill.lower() not in ("#212121", "none"):
            raise ValueError(f"{key}: unexpected fill {fill!r}")
    d = re.search(r'\sd="([^"]+)"', tag)
    if not d:
        raise ValueError(f"{key}: path has no d")
    return d.group(1)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    spec = io.open(sys.argv[1], encoding="utf-8").read()
    keys = keys_from_spec(spec)
    print(f"{len(keys)} distinct icon keys named in the spec")

    glyphs, failed = {}, []
    for i, key in enumerate(sorted(keys), 1):
        url = f"{RAW}/assets/{urllib.parse.quote(concept_dir(key))}/SVG/ic_fluent_{key}_20_regular.svg"
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                glyphs[key] = extract(key, r.read().decode("utf-8"))
        except Exception as e:  # noqa: BLE001 - report every failure, fix them together
            failed.append((key, concept_dir(key), str(e)[:90]))
        if i % 20 == 0:
            print(f"  {i}/{len(keys)}")

    if failed:
        print(f"\n{len(failed)} did not resolve:")
        for key, d, err in failed:
            print(f"  {key:28} dir={d!r:28} {err}")

    body = "".join(f'  {k}: "{v}",\n' for k, v in sorted(glyphs.items()))
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(
        HEADER.format(sha=SHA) + body + "};\n"
    )
    print(f"\nwrote {OUT}: {len(glyphs)} icons")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
